-- Repeatable migration: seed the public activity database.
--
-- A fresh install has an empty activity picker without these — the add-activity
-- screen loads its dropdown from activity_database. They carry their real
-- production UUIDs, so this is idempotent against an existing database and
-- physical_activities.activity_id keeps pointing at the same rows everywhere.
--
-- ON CONFLICT DO NOTHING, deliberately: this seed will never overwrite a row
-- that already exists. Correcting a MET value on a live database is a
-- versioned migration, not an edit here.
--
-- The 449k BLS/FDC food rows are NOT seeded here — those are loaded by
-- tmp/import_bls_to_postgres.py / import_fdc_to_postgres.py.

INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('d30e71ae-e0db-4329-bb43-b0b9d84b8f2d'::uuid, NULL, 'Aerobic', 6.50, 'Fitness', 'high', 'Aerobic-Kurs', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('75e60ce3-42a5-4d73-92a6-fb5853d37a4a'::uuid, NULL, 'Badminton', 5.50, 'Sport', 'moderate', 'Badminton (Freizeit)', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('b5d84834-7000-4007-86c2-47927088a0f1'::uuid, NULL, 'Basketball', 6.50, 'Sport', 'high', 'Basketballspiel', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('46b5b854-e12c-4093-81a6-f4a6e2203043'::uuid, NULL, 'Bodyweight-Training', 4.50, 'Kraft', 'moderate', 'Training mit eigenem Körpergewicht', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('655ae4bb-1a9c-4ad9-8369-79f59c1df1e1'::uuid, NULL, 'Fußball', 7.00, 'Sport', 'high', 'Fußballspiel', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('c06c7990-7cbc-499e-ac0f-ba6efbdbe466'::uuid, NULL, 'Gartenarbeit', 4.00, 'Alltag', 'moderate', 'Gartenarbeit allgemein', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('6324df93-98ee-49b1-9223-4d8578805d4c'::uuid, NULL, 'Gehen (langsam)', 2.50, 'Ausdauer', 'low', 'Spaziergang, gemütliches Tempo', 3.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('28d84852-f166-4b17-8a7c-3b7aee80c619'::uuid, NULL, 'Gehen (normal)', 3.50, 'Ausdauer', 'moderate', 'Normale Gehgeschwindigkeit', 5.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('0c757692-a206-43c2-a034-42495a6694c4'::uuid, NULL, 'Gehen (schnell)', 4.50, 'Ausdauer', 'moderate', 'Zügiges Gehen', 6.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('ed0b7f21-f67f-4d13-b7ce-23268412eb8e'::uuid, NULL, 'Hausarbeit (leicht)', 2.30, 'Alltag', 'low', 'Leichte Hausarbeiten', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('e2ce7d6d-06f1-4e0b-80f7-155ef27271a1'::uuid, NULL, 'Hausarbeit (schwer)', 3.80, 'Alltag', 'moderate', 'Schwere Hausarbeiten', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('03fba5e9-b6b9-44c1-8e40-9a90789df1c7'::uuid, NULL, 'Joggen (langsam)', 7.00, 'Ausdauer', 'high', 'Lockeres Joggen', 8.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('f00bd457-7e30-4b29-b59b-6ca7e27ce01e'::uuid, NULL, 'Kanufahren', 5.00, 'Ausdauer', 'moderate', 'Kanufahren (gemütlich)', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('8b41cc86-0420-4499-8871-1d5d24b37be0'::uuid, NULL, 'Krafttraining (intensiv)', 6.00, 'Kraft', 'high', 'Intensives Gewichtstraining', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('d5aed582-aff5-4774-ade8-76d88b3e1f2d'::uuid, NULL, 'Krafttraining (leicht)', 3.50, 'Kraft', 'moderate', 'Leichtes Gewichtstraining', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('e4dc2223-0d0b-4524-aa5c-30135ddd618c'::uuid, NULL, 'Langlauf', 9.00, 'Ausdauer', 'high', 'Skilanglauf', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('0e0df134-6f5d-4c0e-96cd-df046c145260'::uuid, NULL, 'Laufen (moderat)', 9.00, 'Ausdauer', 'high', 'Mittleres Lauftempo', 10.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('a0674d76-2f54-4151-b470-b5934cacf744'::uuid, NULL, 'Laufen (schnell)', 11.50, 'Ausdauer', 'very_high', 'Schnelles Laufen', 12.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('229a92b0-7a73-470f-86c9-8709fed11a4b'::uuid, NULL, 'Mountainbiken', 8.50, 'Ausdauer', 'high', 'Mountainbike-Tour', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('f516794f-9e92-419f-a8c4-82f5fe32d7f9'::uuid, NULL, 'Pilates', 3.00, 'Fitness', 'low', 'Pilates-Übungen', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('6e8a7699-e035-499f-b83b-f3039c226de7'::uuid, NULL, 'Radfahren (langsam)', 4.00, 'Ausdauer', 'low', 'Gemütliches Radfahren', 12.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('2c5370c6-978a-4872-8a2b-313c5b93ecc5'::uuid, NULL, 'Radfahren (normal)', 6.80, 'Ausdauer', 'moderate', 'Normal Radfahren', 20.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('d630080d-56c6-464d-9d7e-568da698ec84'::uuid, NULL, 'Radfahren (schnell)', 10.00, 'Ausdauer', 'high', 'Zügiges Radfahren', 25.00, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('f2f3e5cd-6e39-465f-859c-dcb2a02c94d1'::uuid, NULL, 'Rasenmähen', 5.50, 'Alltag', 'moderate', 'Rasenmähen (Handmäher)', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('c5a04bd9-ada2-4dff-82fc-a64e2e2b0dda'::uuid, NULL, 'Rudern', 7.00, 'Ausdauer', 'high', 'Rudern (moderat)', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('fc482ccf-fc11-49d9-8dd0-996f2a806ff9'::uuid, NULL, 'Schwimmen (intensiv)', 10.00, 'Ausdauer', 'very_high', 'Intensives Schwimmen', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('6aa32a5b-da62-4684-b268-b43fb56aecd0'::uuid, NULL, 'Schwimmen (langsam)', 5.00, 'Ausdauer', 'moderate', 'Gemütliches Schwimmen', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('9bb0eaf6-530d-4908-9213-a161cd52271b'::uuid, NULL, 'Schwimmen (normal)', 7.00, 'Ausdauer', 'high', 'Normal Schwimmen', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('f7a0e6f5-795c-409c-b7eb-9c4ef4dd1b3b'::uuid, NULL, 'Skifahren (Alpin)', 6.00, 'Sport', 'moderate', 'Alpines Skifahren', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('3fe8d773-77a1-4bc6-b4f3-f7f508fbcee7'::uuid, NULL, 'Snowboarden', 5.50, 'Sport', 'moderate', 'Snowboarden', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('2194042e-785d-49c8-90f8-09a0e603cf7a'::uuid, NULL, 'Spinning', 8.50, 'Fitness', 'high', 'Indoor-Cycling', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('7630158e-4e1b-401f-aa4a-53c390db0af7'::uuid, NULL, 'Sprinten', 15.00, 'Ausdauer', 'very_high', 'Maximale Geschwindigkeit', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('0b42d0b7-e8f2-42e1-a00e-cc1ec9b9fba6'::uuid, NULL, 'Stand-Up Paddling', 4.00, 'Ausdauer', 'moderate', 'SUP (Freizeit)', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('18d0fad4-a05c-42bd-b9b2-9455737fdfb8'::uuid, NULL, 'Tennis', 7.30, 'Sport', 'high', 'Tennisspiel', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('c22da592-5c5f-447e-97a7-4ebbce98d862'::uuid, NULL, 'Treppensteigen', 8.00, 'Alltag', 'high', 'Treppensteigen', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('db65d08e-0bcb-43f9-9487-576f25258e9b'::uuid, NULL, 'Volleyball', 4.00, 'Sport', 'moderate', 'Volleyballspiel', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('d5f03d31-eb9e-4edc-a928-b246c9a7768d'::uuid, NULL, 'Wandern', 5.00, 'Ausdauer', 'moderate', 'Wandern mit Rucksack', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('f89c280d-841d-4dc2-bf68-1c000cc88b38'::uuid, NULL, 'Yoga', 2.50, 'Fitness', 'low', 'Hatha Yoga', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.activity_database (id, user_id, name, met_value, category, intensity, description, avg_speed_kmh, is_public, is_approved, source) VALUES ('7357812c-62dc-47a9-b039-643b928b6d4e'::uuid, NULL, 'Zumba', 6.50, 'Fitness', 'high', 'Zumba-Tanzkurs', NULL, TRUE, TRUE, 'Compendium') ON CONFLICT (id) DO NOTHING;
